create table Books (
	book_Id INT,
	Title VARCHAR(49),
	Author VARCHAR(17),
	Genre VARCHAR(18),
	Availability_status VARCHAR(50)
);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (1, 'Lord of the Flies', 'Hannah Coleman', 'Horror', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (2, 'The Sun Also Rises', 'Samuel Hill', 'Gardening', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (3, 'The Color Purple', 'Zoe Perry', 'Fashion', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (4, 'The Thorn Birds', 'Michael Davis', 'True Crime', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (5, 'The Name of the Wind', 'Victoria Foster', 'Paranormal', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (6, 'The Shining', 'Luke Brooks', 'Chick Lit', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (7, 'The Giver', 'Madison Adams', 'Educational', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (8, 'The Lovely Bones', 'Alyssa Powell', 'Western', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (9, 'The Poisonwood Bible', 'Benjamin Morris', 'Gardening', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (10, 'The Color Purple', 'Owen Price', 'Western', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (11, 'The Alchemist', 'Layla Russell', 'Graphic Novel', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (12, 'The Joy Luck Club', 'Nicholas Wright', 'Horror', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (13, 'The Martian', 'Aria Coleman', 'Biography', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (14, 'The Catcher in the Rye', 'James Thompson', 'Historical Fiction', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (15, 'The Alchemist', 'Madison Adams', 'Educational', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (16, 'The Outsiders', 'Aria Coleman', 'Poetry', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (17, 'The Alchemist', 'Benjamin Morris', 'Fashion', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (18, 'The Brief Wondrous Life of Oscar Wao', 'Daniel Lee', 'Short Stories', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (19, 'The Kite Runner', 'Isaac Hughes', 'Philosophy', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (20, 'The Road Less Traveled', 'Victoria Foster', 'Gardening', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (21, 'The Road', 'Sophie Parker', 'True Crime', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (22, 'The Art of Racing in the Rain', 'Christopher Young', 'Politics', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (23, 'The Lovely Bones', 'Samuel Hill', 'Health', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (24, 'The Road', 'Emily Brown', 'Parenting', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (25, 'The Goldfinch', 'Sophia Lewis', 'Pets', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (26, 'The Alchemist', 'Joshua Ramirez', 'Religion', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (27, 'The Hunger Games', 'David Martinez', 'Mystery', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (28, 'The Maze Runner', 'Sophia Lewis', 'Educational', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (29, 'The Princess Bride', 'John Johnson', 'Biography', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (30, 'The Time Traveler''s Wife', 'Joshua Ramirez', 'Western', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (31, 'The Giver', 'Lily Hall', 'Poetry', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (32, 'To Kill a Mockingbird', 'Daniel Lee', 'Western', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (33, 'The Sun Also Rises', 'Avery Rivera', 'Sports', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (34, 'The Help', 'Daniel Lee', 'Cookbook', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (35, 'The Help', 'Andrew Scott', 'Philosophy', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (36, 'The Goldfinch', 'Dylan Baker', 'Non-Fiction', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (37, 'The Road Less Traveled', 'Alice Smith', 'Crime', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (38, 'The Fault in Our Stars', 'Natalie Reed', 'Humor', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (39, 'The Hunger Games', 'Avery Rivera', 'Science', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (40, 'To Kill a Mockingbird', 'Owen Price', 'Historical Fiction', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (41, 'The Book Thief', 'Lily Hall', 'Young Adult', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (42, 'The Road', 'Olivia Clark', 'Self-Help', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (43, 'The Hobbit', 'Olivia Clark', 'Science', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (44, '1984', 'Hannah Coleman', 'Satire', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (45, 'The Lovely Bones', 'Matthew Harris', 'Philosophy', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (46, 'The Sun Also Rises', 'Matthew Harris', 'Psychology', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (47, 'The Immortal Life of Henrietta Lacks', 'Sophie Parker', 'Romance', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (48, 'The Curious Incident of the Dog in the Night-Time', 'Madison Adams', 'Memoir', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (49, 'The Road', 'Joseph Turner', 'Crafts', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (50, 'The Giver', 'Madison Adams', 'Memoir', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (51, 'The Night Circus', 'Ava White', 'Science Fiction', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (52, 'The Goldfinch', 'Robert Anderson', 'Young Adult', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (53, 'The Great Gatsby', 'Daniel Lee', 'Politics', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (54, 'The Hobbit', 'William Rodriguez', 'Parenting', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (55, 'The Glass Castle', 'Andrew Scott', 'Politics', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (56, 'The Joy Luck Club', 'Aria Coleman', 'DIY', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (57, 'The Giver', 'James Thompson', 'Children''s', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (58, 'The Catcher in the Rye', 'Isabella Edwards', 'Fitness', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (59, 'The Maze Runner', 'Jacob Ward', 'Young Adult', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (60, 'The Brief Wondrous Life of Oscar Wao', 'Ella Torres', 'Travel', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (61, 'The Goldfinch', 'Benjamin Morris', 'History', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (62, 'The Help', 'Robert Anderson', 'Non-Fiction', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (63, 'The Immortal Life of Henrietta Lacks', 'Daniel Lee', 'Adventure', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (64, 'Harry Potter and the Sorcerer''s Stone', 'Andrew Scott', 'Philosophy', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (65, 'The Maze Runner', 'Madison Adams', 'Thriller', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (66, 'The Stand', 'Isaac Hughes', 'Anthology', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (67, 'The Great Gatsby', 'Isaac Hughes', 'Poetry', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (68, 'To Kill a Mockingbird', 'Isaac Hughes', 'Philosophy', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (69, 'The Hobbit', 'Aria Coleman', 'Crafts', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (70, 'The Brief Wondrous Life of Oscar Wao', 'Caleb Gray', 'Paranormal', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (71, 'The Goldfinch', 'Sophia Lewis', 'Politics', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (72, 'The Brief Wondrous Life of Oscar Wao', 'James Thompson', 'Self-Help', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (73, 'The Art of Racing in the Rain', 'Zoe Perry', 'Thriller', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (74, 'Gone Girl', 'David Martinez', 'Travel', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (75, 'The Book Thief', 'Grace Moore', 'Science', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (76, 'The Girl with the Dragon Tattoo', 'Caleb Gray', 'Self-Help', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (77, 'The Maze Runner', 'Owen Price', 'Adventure', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (78, 'The Martian', 'Michael Davis', 'Chick Lit', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (79, 'The Glass Castle', 'David Martinez', 'Biography', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (80, 'The Curious Incident of the Dog in the Night-Time', 'Madison Adams', 'Short Stories', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (81, 'The Help', 'Matthew Harris', 'Young Adult', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (82, 'The Alchemist', 'Avery Rivera', 'Historical Fiction', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (83, 'The Shining', 'Grace Moore', 'Paranormal', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (84, 'The Kite Runner', 'Daniel Lee', 'Politics', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (85, 'The Catcher in the Rye', 'Mia Cooper', 'Religion', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (86, 'The Poisonwood Bible', 'Zoe Perry', 'Parenting', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (87, 'The Book Thief', 'Avery Rivera', 'Philosophy', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (88, 'The Shining', 'Hannah Coleman', 'Biography', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (89, 'The Hunger Games', 'Emma King', 'Parenting', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (90, 'The Poisonwood Bible', 'Daniel Lee', 'Historical Fiction', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (91, 'Brave New World', 'Samuel Hill', 'Satire', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (92, 'The Help', 'Dylan Baker', 'Short Stories', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (93, 'The Martian', 'Daniel Lee', 'Classic', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (94, 'The Picture of Dorian Gray', 'Ella Torres', 'Religion', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (95, 'The Martian', 'Ethan Nelson', 'Health', false);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (96, 'The Outsiders', 'Joshua Ramirez', 'Gardening', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (97, 'The Catcher in the Rye', 'Aria Coleman', 'Cooking', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (98, 'The Princess Bride', 'Hannah Coleman', 'Cooking', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (99, 'The Outsiders', 'Jacob Ward', 'Fantasy', true);
insert into Books (book_Id, Title, Author, Genre, Availability_status) values (100, 'The Girl with the Dragon Tattoo', 'Jack Murphy', 'Sports', true);
